services:
  application:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: application
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/certificate/phpislife.com.br.crt:/etc/ssl/certs/phpislife.com.br.crt
      - /etc/certificate/phpislife.com.br.key:/etc/ssl/private/phpislife.com.br.key
    networks:
      - laravel_app
networks:
  laravel_app:
    driver: bridge
